//! HTML treemap visualization generator.
//!
//! Generates a standalone HTML file with an interactive treemap of findings.

use std::collections::BTreeMap;
use std::path::Path;

use deslop_types::enums::Status;
use deslop_types::finding::Finding;

/// Generate a standalone HTML file with an interactive findings treemap.
pub fn generate_html_report(
    findings: &BTreeMap<String, Finding>,
    files: &[String],
    scores: &serde_json::Value,
    output_path: &Path,
) -> Result<(), std::io::Error> {
    let html = build_html(findings, files, scores);
    std::fs::write(output_path, html)
}

fn build_html(
    findings: &BTreeMap<String, Finding>,
    files: &[String],
    scores: &serde_json::Value,
) -> String {
    // Aggregate data for visualization
    let mut file_data: Vec<serde_json::Value> = Vec::new();
    let mut detector_counts: BTreeMap<String, usize> = BTreeMap::new();
    let mut tier_counts = [0usize; 4];

    for file in files {
        let file_findings: Vec<&Finding> = findings
            .values()
            .filter(|f| f.file == *file && f.status == Status::Open)
            .collect();

        if !file_findings.is_empty() {
            file_data.push(serde_json::json!({
                "name": file,
                "findings": file_findings.len(),
            }));
        }

        for f in &file_findings {
            *detector_counts.entry(f.detector.clone()).or_default() += 1;
            let tier_idx = match f.tier {
                deslop_types::enums::Tier::AutoFix => 0,
                deslop_types::enums::Tier::QuickFix => 1,
                deslop_types::enums::Tier::Judgment => 2,
                deslop_types::enums::Tier::MajorRefactor => 3,
            };
            tier_counts[tier_idx] += 1;
        }
    }

    let open_count = findings
        .values()
        .filter(|f| f.status == Status::Open)
        .count();

    let detector_data: Vec<serde_json::Value> = detector_counts
        .iter()
        .map(|(name, count)| serde_json::json!({"name": name, "count": count}))
        .collect();

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Desloppify Report</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #1a1a2e; color: #e0e0e0; }}
  .header {{ padding: 24px 32px; background: #16213e; border-bottom: 2px solid #0f3460; }}
  .header h1 {{ font-size: 24px; color: #e94560; }}
  .header .scores {{ margin-top: 12px; font-size: 14px; }}
  .header .scores span {{ margin-right: 24px; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; padding: 20px 32px; }}
  .card {{ background: #16213e; border-radius: 8px; padding: 20px; border: 1px solid #0f3460; }}
  .card h2 {{ font-size: 16px; color: #e94560; margin-bottom: 12px; }}
  .bar {{ display: flex; align-items: center; margin: 4px 0; }}
  .bar-label {{ width: 180px; font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  .bar-fill {{ height: 16px; background: #e94560; border-radius: 3px; min-width: 2px; }}
  .bar-count {{ margin-left: 8px; font-size: 12px; color: #999; }}
  .tier-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
  .tier-box {{ background: #1a1a2e; border-radius: 6px; padding: 12px; text-align: center; }}
  .tier-box .count {{ font-size: 28px; font-weight: bold; color: #e94560; }}
  .tier-box .label {{ font-size: 11px; color: #999; margin-top: 4px; }}
  .summary {{ padding: 20px 32px; font-size: 13px; color: #999; }}
</style>
</head>
<body>
<div class="header">
  <h1>Desloppify Report</h1>
  <div class="scores">
    <span>Overall: {overall}</span>
    <span>Objective: {objective}</span>
    <span>Strict: {strict}</span>
    <span>Open Findings: {open_count}</span>
    <span>Files Scanned: {file_count}</span>
  </div>
</div>
<div class="grid">
  <div class="card">
    <h2>Findings by Tier</h2>
    <div class="tier-grid">
      <div class="tier-box"><div class="count">{t1}</div><div class="label">T1 AutoFix</div></div>
      <div class="tier-box"><div class="count">{t2}</div><div class="label">T2 QuickFix</div></div>
      <div class="tier-box"><div class="count">{t3}</div><div class="label">T3 Judgment</div></div>
      <div class="tier-box"><div class="count">{t4}</div><div class="label">T4 Major</div></div>
    </div>
  </div>
  <div class="card">
    <h2>Top Detectors</h2>
    {detector_bars}
  </div>
  <div class="card" style="grid-column: span 2;">
    <h2>Files with Most Findings</h2>
    {file_bars}
  </div>
</div>
<div class="summary">Generated by desloppify</div>
</body>
</html>"#,
        overall = scores
            .get("overall")
            .and_then(|v| v.as_f64())
            .unwrap_or(0.0),
        objective = scores
            .get("objective")
            .and_then(|v| v.as_f64())
            .unwrap_or(0.0),
        strict = scores.get("strict").and_then(|v| v.as_f64()).unwrap_or(0.0),
        open_count = open_count,
        file_count = files.len(),
        t1 = tier_counts[0],
        t2 = tier_counts[1],
        t3 = tier_counts[2],
        t4 = tier_counts[3],
        detector_bars = render_bars(&detector_data, 10),
        file_bars = render_bars(&file_data.iter().take(15).cloned().collect::<Vec<_>>(), 15),
    )
}

fn render_bars(data: &[serde_json::Value], max_items: usize) -> String {
    if data.is_empty() {
        return "<div style=\"color:#666\">No data</div>".to_string();
    }

    let max_count = data
        .iter()
        .take(max_items)
        .filter_map(|d| {
            d.get("count")
                .or_else(|| d.get("findings"))
                .and_then(|v| v.as_u64())
        })
        .max()
        .unwrap_or(1) as f64;

    let mut html = String::new();
    for item in data.iter().take(max_items) {
        let name = item.get("name").and_then(|v| v.as_str()).unwrap_or("?");
        let count = item
            .get("count")
            .or_else(|| item.get("findings"))
            .and_then(|v| v.as_u64())
            .unwrap_or(0);
        let width = (count as f64 / max_count * 200.0).max(2.0);

        html.push_str(&format!(
            "<div class=\"bar\"><span class=\"bar-label\">{name}</span>\
             <div class=\"bar-fill\" style=\"width:{width}px\"></div>\
             <span class=\"bar-count\">{count}</span></div>"
        ));
    }
    html
}

#[cfg(test)]
mod tests {
    use super::*;
    use deslop_types::enums::{Confidence, Tier};

    fn make_finding(file: &str, detector: &str) -> Finding {
        Finding {
            id: format!("{detector}::{file}::1"),
            detector: detector.into(),
            file: file.into(),
            tier: Tier::QuickFix,
            confidence: Confidence::High,
            summary: "test".into(),
            detail: serde_json::json!({}),
            status: Status::Open,
            note: None,
            first_seen: String::new(),
            last_seen: String::new(),
            resolved_at: None,
            reopen_count: 0,
            suppressed: false,
            suppressed_at: None,
            suppression_pattern: None,
            resolution_attestation: None,
            lang: None,
            zone: None,
            extra: BTreeMap::new(),
        }
    }

    #[test]
    fn generates_html() {
        let mut findings = BTreeMap::new();
        let f = make_finding("src/main.rs", "security");
        findings.insert(f.id.clone(), f);
        let files = vec!["src/main.rs".to_string()];
        let scores = serde_json::json!({"overall": 85.0, "objective": 90.0, "strict": 80.0});
        let html = build_html(&findings, &files, &scores);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("Desloppify Report"));
        assert!(html.contains("85"));
    }

    #[test]
    fn empty_report() {
        let html = build_html(&BTreeMap::new(), &[], &serde_json::json!({}));
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("No data"));
    }
}
